CREATE DATABASE IF NOT EXISTS Battleship;
USE Battleship;

CREATE TABLE Users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    wins INT NOT NULL,
    losses INT NOT NULL
);